name: Java CI with Maven - Test and package
on: pull_request
env:
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-
      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: sonar
      - name: Setup Java
        uses: "actions/setup-java@v4"
        with:
          distribution: 'corretto'
          java-version: '21'
      - name: Maven build and test
        run: "mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=$(echo ${{ github.repository }} | sed 's-/-_-')"