name: Bonjour
on: push
jobs:
  Salutations:
    name: Salutations
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        env:
          personneASaluer: 'Mon voisin Totoro'
        run: echo "Bonjour ${personneASaluer}"
      - name: L'heure de la Salutations
        run: echo "L'heure était ${date}"
